# Generated by Django 4.1.3 on 2022-12-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='amateur_class',
            field=models.CharField(choices=[('base', '2'), ('advanced', '1')], max_length=8),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('rules', 'Rules'), ('regulations', 'Regulations')], max_length=11),
        ),
    ]
