# Generated by Django 4.1.3 on 2022-12-03 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='call_sign',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
