# Generated by Django 4.1.3 on 2022-12-13 12:57

import django.core.validators
from django.db import migrations, models
import ham_radio_quiz.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(5), ham_radio_quiz.validators.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(5), ham_radio_quiz.validators.validate_letters_only]),
        ),
    ]
