# Generated by Django 4.1.3 on 2022-12-10 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examination', '0002_generatedquestionsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='user_test_id',
        ),
        migrations.AddField(
            model_name='exammodel',
            name='user_test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
