# Generated by Django 4.1.3 on 2022-12-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_remove_exammodel_user_test_question_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammodel',
            old_name='user_test_question_id',
            new_name='user_test_question',
        ),
    ]
