# Generated by Django 4.1.3 on 2022-12-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_rename_user_test_question_id_exammodel_user_test_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammodel',
            name='user_test_question',
        ),
    ]
