# Generated by Django 4.1.3 on 2022-12-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0007_exammodel_user_test_question_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_exam', models.CharField(max_length=15)),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('exam_is_passed', models.BooleanField()),
                ('points', models.PositiveIntegerField()),
            ],
        ),
    ]
